version: 2.1
jobs:
  compile:
   docker:
      - image: panchajanya1999/archlinux:latest
   steps:
      - run:
          command: |
            pacman -Sy --noconfirm git bc lld ccache llvm inetutils python3 flex bison libc++ libxml2 python-pip zip wget cpio jdk-openjdk tzdata && python3 -m pip install networkx && pip3 install --upgrade gupload
            git clone --depth=1 https://github.com/missgoin/vayu4.git -b main builder_kernel
            cd builder_kernel
            bash .circleci/vayu.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
