>version: 2.1
jobs:
  compile:
   docker:
      - image: panchajanya1999/archlinux:latest
   steps:
      - run:
          command: |
            pacman -Syu --needed --noconfirm git wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python zip github-cli fortune-mod ccache
            git clone --depth=1 https://github.com/missgoin/whyred2.git -b main builder_kernel
            cd builder_kernel
            bash .circleci/whyred.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
