version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:jammy-20211029
   steps:
      - run:
          command: |
            apt update && apt upgrade -y
            apt install -f -y git
            ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
            git clone --depth=1 https://github.com/missgoin/whyred2.git -b main builder_kernel
            cd builder_kernel
            cp -af sources.list /etc/apt/
            cp -af 99own /etc/apt/apt.conf.d/
            apt install -y bc bison build-essential ccache cpio libdebuginfod-dev curl flex g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 tmate ssh neofetch ssh-client patch libtinfo5
            bash .circleci/whyred.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
